### ISSUE TITLE
API always returning code 0

### ISSUE THREAD

**Issue by ttiagojm** [ttiagojm/Noted#9]
I test it out https://noted-api.onrender.com/statistics and it returns code 0. 

Try to return another code to verify if the daemon got it.

**Comment by ttiagojm** [comment]
GET it's working now as expected, but POST still not working, returning  with the following error:
`{"statusCode":500,"code":"P2003","error":"Internal Server Error","message":"\nInvalid prisma.statistics.create() invocation:\n\n\nForeign key constraint failed on the field: Statistics_UserId_fkey (index)"}`

**Comment by GoncalojmRosa** [comment]
I need to change that route so that i can create or update data on DB, based on data received on request body.

**Comment by ttiagojm** [comment]
Can you just return a random code, just to verify if the socket is working? @GoncalojmRosa
